# Generated by Django 5.0.6 on 2024-07-16 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(db_column='idCargo', primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(db_column='idCliente', primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=20)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('cli_apellido_paterno', models.CharField(max_length=20)),
                ('cli_apellido_materno', models.CharField(max_length=20)),
                ('numero_celular', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id_mecanico', models.AutoField(db_column='idMecanico', primary_key=True, serialize=False)),
                ('nombre_mecanico', models.CharField(max_length=20)),
                ('mec_apellido_paterno', models.CharField(max_length=20)),
                ('mec_apellido_materno', models.CharField(max_length=20)),
                ('numero_celular', models.CharField(max_length=45)),
                ('id_cargo', models.ForeignKey(db_column='idCargo', on_delete=django.db.models.deletion.CASCADE, to='informe.cargo')),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_inf_tec', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('orden_servicio', models.CharField(max_length=100)),
                ('trabajo_solicitado', models.TextField(blank=True, null=True)),
                ('trabajos_realizados', models.TextField(blank=True, null=True)),
                ('evaluacion', models.TextField(blank=True, null=True)),
                ('enlaces_fotos', models.URLField(blank=True, null=True)),
                ('enlaces_videos', models.URLField(blank=True, null=True)),
                ('conclusion', models.TextField(blank=True, null=True)),
                ('id_cliente', models.ForeignKey(db_column='idCliente', on_delete=django.db.models.deletion.CASCADE, to='informe.cliente')),
                ('id_mecanico', models.ForeignKey(db_column='idMecanico', on_delete=django.db.models.deletion.CASCADE, to='informe.mecanico')),
            ],
        ),
    ]
