# Generated by Django 4.1.2 on 2024-07-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.AutoField(db_column='idPresupuesto', primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=20)),
                ('rut_cliente', models.CharField(max_length=15)),
                ('direccion_cliente', models.CharField(max_length=50)),
                ('telefono_cliente', models.CharField(max_length=20)),
                ('correo_cliente', models.CharField(max_length=40)),
                ('año_vehiculo', models.CharField(max_length=4)),
                ('marca_vehiculo', models.CharField(max_length=20)),
                ('modelo_vehiculo', models.CharField(max_length=20)),
                ('trabajo_solicitado', models.TextField()),
                ('respaldo_fotografico', models.URLField()),
                ('observaciones', models.TextField()),
            ],
        ),
    ]
