# Generated by Django 4.1.2 on 2024-07-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0002_presupuesto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='año_vehiculo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='correo_cliente',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='id_presupuesto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='nombre_cliente',
            field=models.CharField(max_length=60),
        ),
    ]
