# Generated by Django 4.1.2 on 2024-07-18 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informe', '0004_solicitud'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='correo_cliente_sol',
            new_name='correo_electrónico',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='nombre_cliente_sol',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='solicitud',
            old_name='telefono_cliente_sol',
            new_name='telefono',
        ),
    ]
